fix ImportError: cannot import name FormDefinition
When DEBUG=False importing FormDefinition causes circular importing of User model.
Here is a "fix".